### ISSUE TITLE
Typings

### ISSUE THREAD

**Issue by dwilt** [andyrichardson/passport-workos#2]
hey @andyrichardson thanks for putting this together. Any reason why the [`Verify` function](https://github.com/andyrichardson/passport-workos/blob/master/src/index.ts#L11) is typed as `any`? Also, mind if I put up a PR to try and fix that typing as well as `export` `Verify` and `Options`?

**Comment by dwilt** [comment]
@andyrichardson put up a PR. Just a heads up, when I run `npm i` on `master`, I get changes to the `package-lock.json`. You might need to run `npm i` and then commit that change.

**Comment by andyrichardson** [comment]
Marking as done :+1: Thanks for the contribution
