### ISSUE TITLE
Organization support

### ISSUE THREAD

**Issue by dwilt** [andyrichardson/passport-workos#9]
Is there any reason why the [query params check in `_loginAttempt`](https://github.com/andyrichardson/passport-workos/blob/master/src/index.ts#L38) isn't also looking for `organization`? The [docs say](https://workos.com/docs/sso/guide/integrate-with-app/add-an-endpoint-to-initiate-sso) it's able to be passed into `getAuthorizationURL`.

**Comment by andyrichardson** [comment]
Off the top of my head, I can't think of a reason why not to support it 👍

**Comment by dwilt** [comment]
mind if I add a PR?
